name: Run SauceDemo TestNG Suite Manually

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Clean reports (Extent + Screenshots)
        run: |
          rm -rf reports/htmlReports/*
          rm -rf reports/screenshot/*

      - name: Run SauceDemo TestNG Suite
        run: mvn clean test -DsuiteXmlFile=TestRunner/SauceDemo.xml -Dheadless=true

      - name: Debug - List generated Extent report
        run: ls -R reports/htmlReports || echo "Extent report not found"

      - name: Print Surefire failure logs if test fails
        if: failure()
        run: |
          echo "📄 TestNG Failure Logs:"
          cat target/surefire-reports/*.txt || echo "No logs found"

      - name: Archive Test Results (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: target/surefire-reports/

      - name: Upload Extent HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report-${{ github.run_number }}
          path: reports/htmlReports/
